/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package final_gui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author USER
 */
public class FinaloGUIOSM extends javax.swing.JFrame {

    /**
     * Creates new form FinaloGUIOSM
     */
    public FinaloGUIOSM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mainpanel_for_SubTotal = new javax.swing.JPanel();
        label_For_SubTotal = new javax.swing.JLabel();
        TextFied_For_Obtained_Marks = new javax.swing.JTextField();
        Button_For_Submt = new javax.swing.JButton();
        panel_For_Sample_Answer = new javax.swing.JPanel();
        Drop_Down = new javax.swing.JComboBox<>();
        label_Heading_Sample_Answer = new javax.swing.JLabel();
        Label_For_Sample_Answer = new javax.swing.JLabel();
        Main_Panel_For_Buttons_SC = new javax.swing.JPanel();
        First_Button_SC = new javax.swing.JButton();
        Previous_Button_SC = new javax.swing.JButton();
        Next_Button_SC = new javax.swing.JButton();
        Last_Button_SC = new javax.swing.JButton();
        Main_Panel_For_Buttons_SA = new javax.swing.JPanel();
        First_Botton_SA = new javax.swing.JButton();
        previous_Button_SA = new javax.swing.JButton();
        next_Button_SA = new javax.swing.JButton();
        last_Button_SA = new javax.swing.JButton();
        panel_For_StuCopy_Button = new javax.swing.JPanel();
        next_Copy_Button = new javax.swing.JButton();
        label_For_Heading_Obtained_Marks = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Sroll_panel_For_Obt_Marks = new javax.swing.JPanel();
        label_Stu_Ans_Heading = new javax.swing.JLabel();
        Label_for_Student_copy = new javax.swing.JLabel();
        tnc_LabelHeading = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        NOC_label = new javax.swing.JLabel();
        txt_checked = new javax.swing.JTextField();
        Noc_remaining_Label = new javax.swing.JLabel();
        txt_left = new javax.swing.JTextField();
        dd_copyno = new javax.swing.JComboBox<>();
        Noc_remaining_Label1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Mainpanel_for_SubTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Mainpanel_for_SubTotal.setName("Panel_for_overall_Subtotal"); // NOI18N

        label_For_SubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_For_SubTotal.setText("Sub Total : ");
        label_For_SubTotal.setName("label_contaning_heading_\"Sub_total\""); // NOI18N

        TextFied_For_Obtained_Marks.setEditable(false);
        TextFied_For_Obtained_Marks.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TextFied_For_Obtained_Marks.setName("non_editable_Text_Field_For_Obtained_marks"); // NOI18N

        Button_For_Submt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Button_For_Submt.setText("SUBMIT");
        Button_For_Submt.setName("Submit_button"); // NOI18N

        javax.swing.GroupLayout Mainpanel_for_SubTotalLayout = new javax.swing.GroupLayout(Mainpanel_for_SubTotal);
        Mainpanel_for_SubTotal.setLayout(Mainpanel_for_SubTotalLayout);
        Mainpanel_for_SubTotalLayout.setHorizontalGroup(
            Mainpanel_for_SubTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Mainpanel_for_SubTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_For_SubTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextFied_For_Obtained_Marks, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(Button_For_Submt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Mainpanel_for_SubTotalLayout.setVerticalGroup(
            Mainpanel_for_SubTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Mainpanel_for_SubTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Mainpanel_for_SubTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_For_SubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Mainpanel_for_SubTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TextFied_For_Obtained_Marks, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                        .addComponent(Button_For_Submt)))
                .addContainerGap())
        );

        panel_For_Sample_Answer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_For_Sample_Answer.setName("Main_panel_for_sample_answer"); // NOI18N

        Drop_Down.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28" }));
        Drop_Down.setName("Drop_down"); // NOI18N

        label_Heading_Sample_Answer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_Heading_Sample_Answer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Heading_Sample_Answer.setText("SAMPLE ANSWER");
        label_Heading_Sample_Answer.setName("Label_For_heading_SampleAnswer"); // NOI18N

        Label_For_Sample_Answer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panel_For_Sample_AnswerLayout = new javax.swing.GroupLayout(panel_For_Sample_Answer);
        panel_For_Sample_Answer.setLayout(panel_For_Sample_AnswerLayout);
        panel_For_Sample_AnswerLayout.setHorizontalGroup(
            panel_For_Sample_AnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_For_Sample_AnswerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_For_Sample_AnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_For_Sample_Answer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel_For_Sample_AnswerLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Drop_Down, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label_Heading_Sample_Answer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_For_Sample_AnswerLayout.setVerticalGroup(
            panel_For_Sample_AnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_For_Sample_AnswerLayout.createSequentialGroup()
                .addComponent(label_Heading_Sample_Answer, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Drop_Down, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_For_Sample_Answer, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Main_Panel_For_Buttons_SC.setName("panel containing buttons for student copy"); // NOI18N

        First_Button_SC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        First_Button_SC.setText("First");
        First_Button_SC.setName("First button"); // NOI18N

        Previous_Button_SC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Previous_Button_SC.setText("Previous");

        Next_Button_SC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Next_Button_SC.setText("Next");
        Next_Button_SC.setName("Next Button"); // NOI18N

        Last_Button_SC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Last_Button_SC.setText("Last");
        Last_Button_SC.setName("Last button"); // NOI18N

        javax.swing.GroupLayout Main_Panel_For_Buttons_SCLayout = new javax.swing.GroupLayout(Main_Panel_For_Buttons_SC);
        Main_Panel_For_Buttons_SC.setLayout(Main_Panel_For_Buttons_SCLayout);
        Main_Panel_For_Buttons_SCLayout.setHorizontalGroup(
            Main_Panel_For_Buttons_SCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Main_Panel_For_Buttons_SCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(First_Button_SC, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(Previous_Button_SC, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(Next_Button_SC, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(Last_Button_SC, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Main_Panel_For_Buttons_SCLayout.setVerticalGroup(
            Main_Panel_For_Buttons_SCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Main_Panel_For_Buttons_SCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Main_Panel_For_Buttons_SCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Last_Button_SC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Next_Button_SC, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .addComponent(First_Button_SC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Previous_Button_SC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Main_Panel_For_Buttons_SA.setName("Panel_for_Buttons_For_Sample_Answer"); // NOI18N

        First_Botton_SA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        First_Botton_SA.setText("First");
        First_Botton_SA.setName("First_button"); // NOI18N

        previous_Button_SA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        previous_Button_SA.setText("Previous");
        previous_Button_SA.setName("Previous_button"); // NOI18N

        next_Button_SA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        next_Button_SA.setText("Next");
        next_Button_SA.setName("Next_button"); // NOI18N

        last_Button_SA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        last_Button_SA.setText("Last");
        last_Button_SA.setName("Last_button"); // NOI18N

        javax.swing.GroupLayout Main_Panel_For_Buttons_SALayout = new javax.swing.GroupLayout(Main_Panel_For_Buttons_SA);
        Main_Panel_For_Buttons_SA.setLayout(Main_Panel_For_Buttons_SALayout);
        Main_Panel_For_Buttons_SALayout.setHorizontalGroup(
            Main_Panel_For_Buttons_SALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Main_Panel_For_Buttons_SALayout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addComponent(First_Botton_SA, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(previous_Button_SA, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(next_Button_SA, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(last_Button_SA, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Main_Panel_For_Buttons_SALayout.setVerticalGroup(
            Main_Panel_For_Buttons_SALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Main_Panel_For_Buttons_SALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Main_Panel_For_Buttons_SALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(last_Button_SA, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(next_Button_SA, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(previous_Button_SA, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(First_Botton_SA, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_For_StuCopy_Button.setName("Button For Submit and Next Copy"); // NOI18N

        next_Copy_Button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        next_Copy_Button.setText("NEXT COPY");
        next_Copy_Button.setName("Next Copy Button"); // NOI18N

        javax.swing.GroupLayout panel_For_StuCopy_ButtonLayout = new javax.swing.GroupLayout(panel_For_StuCopy_Button);
        panel_For_StuCopy_Button.setLayout(panel_For_StuCopy_ButtonLayout);
        panel_For_StuCopy_ButtonLayout.setHorizontalGroup(
            panel_For_StuCopy_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_For_StuCopy_ButtonLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(next_Copy_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        panel_For_StuCopy_ButtonLayout.setVerticalGroup(
            panel_For_StuCopy_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_For_StuCopy_ButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(next_Copy_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        label_For_Heading_Obtained_Marks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_For_Heading_Obtained_Marks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_For_Heading_Obtained_Marks.setText("OBTAINED MARKS");
        label_For_Heading_Obtained_Marks.setName("label_for_heading_obtained_marks"); // NOI18N

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        Sroll_panel_For_Obt_Marks.setName("scroll_panel_for_obtained_marks"); // NOI18N

        javax.swing.GroupLayout Sroll_panel_For_Obt_MarksLayout = new javax.swing.GroupLayout(Sroll_panel_For_Obt_Marks);
        Sroll_panel_For_Obt_Marks.setLayout(Sroll_panel_For_Obt_MarksLayout);
        Sroll_panel_For_Obt_MarksLayout.setHorizontalGroup(
            Sroll_panel_For_Obt_MarksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Sroll_panel_For_Obt_MarksLayout.setVerticalGroup(
            Sroll_panel_For_Obt_MarksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 587, Short.MAX_VALUE)
        );

        jScrollPane3.setViewportView(Sroll_panel_For_Obt_Marks);

        label_Stu_Ans_Heading.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_Stu_Ans_Heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Stu_Ans_Heading.setText("STUDENT ANSWER SHEET");
        label_Stu_Ans_Heading.setName("label_for_heading_\"Stydent_answer_Sheet\""); // NOI18N

        Label_for_Student_copy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tnc_LabelHeading.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tnc_LabelHeading.setText("Total Number of Copy:");

        txt_total.setEditable(false);
        txt_total.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        NOC_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NOC_label.setText("Number of Copy Checked:");

        txt_checked.setEditable(false);
        txt_checked.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        Noc_remaining_Label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Noc_remaining_Label.setText("Number of copy Remaining:");

        txt_left.setEditable(false);

        dd_copyno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Noc_remaining_Label1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Noc_remaining_Label1.setText("Copy No.");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("LOAD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(Main_Panel_For_Buttons_SC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Main_Panel_For_Buttons_SA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panel_For_StuCopy_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(label_Stu_Ans_Heading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Label_for_Student_copy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tnc_LabelHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(45, 45, 45)
                                    .addComponent(NOC_label)
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_checked, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(44, 44, 44)
                                    .addComponent(Noc_remaining_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_left, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(173, 173, 173)
                                    .addComponent(Noc_remaining_Label1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dd_copyno, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Mainpanel_for_SubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane3)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(panel_For_Sample_Answer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label_For_Heading_Obtained_Marks, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_For_Heading_Obtained_Marks, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Mainpanel_for_SubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(panel_For_Sample_Answer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tnc_LabelHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NOC_label, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_checked, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Noc_remaining_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dd_copyno, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_left, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Noc_remaining_Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_Stu_Ans_Heading, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Label_for_Student_copy, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Main_Panel_For_Buttons_SA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Main_Panel_For_Buttons_SC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(panel_For_StuCopy_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(286, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

                                                                                //LOAD BUTTON EVENT    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");  
  
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","root");  
                Statement stmt1=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);  

                  
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinaloGUIOSM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinaloGUIOSM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinaloGUIOSM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinaloGUIOSM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinaloGUIOSM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_For_Submt;
    private javax.swing.JComboBox<String> Drop_Down;
    private javax.swing.JButton First_Botton_SA;
    private javax.swing.JButton First_Button_SC;
    private javax.swing.JLabel Label_For_Sample_Answer;
    private javax.swing.JLabel Label_for_Student_copy;
    private javax.swing.JButton Last_Button_SC;
    private javax.swing.JPanel Main_Panel_For_Buttons_SA;
    private javax.swing.JPanel Main_Panel_For_Buttons_SC;
    private javax.swing.JPanel Mainpanel_for_SubTotal;
    private javax.swing.JLabel NOC_label;
    private javax.swing.JButton Next_Button_SC;
    private javax.swing.JLabel Noc_remaining_Label;
    private javax.swing.JLabel Noc_remaining_Label1;
    private javax.swing.JButton Previous_Button_SC;
    private javax.swing.JPanel Sroll_panel_For_Obt_Marks;
    private javax.swing.JTextField TextFied_For_Obtained_Marks;
    private javax.swing.JComboBox<String> dd_copyno;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel label_For_Heading_Obtained_Marks;
    private javax.swing.JLabel label_For_SubTotal;
    private javax.swing.JLabel label_Heading_Sample_Answer;
    private javax.swing.JLabel label_Stu_Ans_Heading;
    private javax.swing.JButton last_Button_SA;
    private javax.swing.JButton next_Button_SA;
    private javax.swing.JButton next_Copy_Button;
    private javax.swing.JPanel panel_For_Sample_Answer;
    private javax.swing.JPanel panel_For_StuCopy_Button;
    private javax.swing.JButton previous_Button_SA;
    private javax.swing.JLabel tnc_LabelHeading;
    private javax.swing.JTextField txt_checked;
    private javax.swing.JTextField txt_left;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
